version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.18
  - dependency-name: source-map-loader
    versions:
    - 2.0.1
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
  - dependency-name: webpack
    versions:
    - 5.21.2
    - 5.22.0
  - dependency-name: postcss
    versions:
    - 8.2.6
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: mongoose
    versions:
    - 5.11.15
  - dependency-name: chai
    versions:
    - 4.3.0
