name: tests

on: [push, pull_request]

jobs:
  tests:
    name: node ${{ matrix.node-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [15, 14]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - if: matrix.os == 'windows-latest'
        name: patch node gyp on windows to support Visual Studio 2019
        shell: powershell
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn@1
      - run: npm i -g lerna@latest
      - run: yarn --frozen-lockfile
      - run: lerna run test
